### ISSUE TITLE
Include an example screenshot in the documentation

### ISSUE THREAD

**Issue by Areiser** [ArcticZeroo/flutter-search-bar#1]
Hi,
this looks promising. It would be great if you can include a screenshot in your Readme/documentation so people don't have to set it all up until they see what it looks like :)

**Comment by ArcticZeroo** [comment]
Sure, I took some screenshots the other day and just forgot to add them in. I'll do it in a moment.

**Comment by ArcticZeroo** [comment]
Alright, example screenshots are now in the readme as of https://github.com/ArcticZeroo/flutter-search-bar/commit/7e3602ca4f0a03b3f1cc7bbda8bf6ed30e61be95 . Added a few to show default state and how the `inBar` option affects the aesthetics.
