### ISSUE TITLE
Support for RTL layout and languages

### ISSUE THREAD

**Issue by salehahmedZ** [ArcticZeroo/flutter-search-bar#11]
Maybe I didn't know how to implement this, but doesn't this plugin support RTL languages like Arabic and Hebrew etc?

**Comment by ArcticZeroo** [comment]
What happens when you try to use rtl input?

**Comment by salehahmedZ** [comment]
when I entered an Arabic text everything works fine except that the search text field and suggestions list should be from RTL instead of LTR.

**Comment by ArcticZeroo** [comment]
Hmm, I'm not sure of a good way to solve that. 
My initial thought would be to simply add an option when instantiating the SearchBar class which allows the dev to toggle between RTL and LTR, but that's potentially problematic for apps that want to support LTR _and_ RTL languages

**Comment by ArcticZeroo** [comment]
@salehahmedZ should be fixed with 2.0.1

**Comment by salehahmedZ** [comment]
You are amazing. Thanks!
