### ISSUE TITLE
Localizable string to hintText

### ISSUE THREAD

**Issue by rcpassos** [ArcticZeroo/flutter-search-bar#14]
I can't set the **hintText** based on [Internationalization](https://flutter.io/tutorials/internationalization/) because I need to instantiate the _searchBar on the constructor and here I can't access to BuildContext.
Any idea?

**Comment by ArcticZeroo** [comment]
Should be a fairly simple fix; will make the hintText property non-final so you can assign to it

**Comment by ArcticZeroo** [comment]
Sorry for the delay. Fixed with https://github.com/ArcticZeroo/flutter-search-bar/commit/ba56969f73b1c6740b2a8aa31f06b14da1ebbf23
