### ISSUE TITLE
Error when trying example on Flutter 0.2.8 and Dart 2.0.0

### ISSUE THREAD

**Issue by AppleEducate** [ArcticZeroo/flutter-search-bar#15]
The following assertion was thrown building Builder:
type '(() => void) => void' is not a subtype of type '(dynamic) => void'
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.

**Comment by ArcticZeroo** [comment]
I cannot reproduce on my Pixel 2 XL;
```
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] Connected devices (1 available)

• No issues found!
```
I did find an issue with the search bar package being missing from the pubspec, I don't think that would cause it though (you'd be getting an error regarding being unable to resolve the import)

**Comment by AppleEducate** [comment]
I think I got it to resolve, but not sure what I did. I will reopen If it happens again.
