### ISSUE TITLE
Does not allow user input

### ISSUE THREAD

**Issue by bjornbjorn** [ArcticZeroo/flutter-search-bar#2]
Hi,

I'm testing your search bar and I see it does not allow user input. Everything is working fine except for the fact that I can't type anything in the textfield. I guess a fix is to update InputValue in setState() ?

**Comment by ArcticZeroo** [comment]
I can't reproduce on a Pixel XL running O, can you post some code? What platform are you on?

**Comment by bjornbjorn** [comment]
Sorry, it must've been a glitch in my emulator or something - when restarting it today I'm able to type in the textfield (iOS btw).
