### ISSUE TITLE
No support for SliverAppBar

### ISSUE THREAD

**Issue by IhorKlimov** [ArcticZeroo/flutter-search-bar#20]
SliverAppBar is currently not supported

**Comment by ArcticZeroo** [comment]
Sorry for late reply, never got this notification.

This should be a relatively simple change, the AppBar callback will just have to be less strict. Will do when I get a chance, or feel free to make a PR. Should just have to change the return type to StatefulWidget.

**Comment by IhorKlimov** [comment]
@ArcticZeroo Oh yeah, totally. It took me just a few mins. Just wanted to create an issue for it

**Comment by ArcticZeroo** [comment]
Got it, thanks! Feel free to make that PR if you've already got it down :) otherwise I can pull it in tomorrow if you don't get a chance.

**Comment by ArcticZeroo** [comment]
Fixed in https://github.com/ArcticZeroo/flutter-search-bar/commit/0441e951228257ccbe284dc07ad85664487e0cda
