### ISSUE TITLE
No support for dart version > 2.0.0

### ISSUE THREAD

**Issue by foosionsapps** [ArcticZeroo/flutter-search-bar#24]
environment:
  sdk: '>=1.20.1 <=2.0.0'

I'm using Dart version 2.1.0-dev.1.0 and when I want to update the library to the latest version I get this error:
The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7.

Because "your app" depends on flutter_search_bar >=1.0.3 which requires SDK version >=1.20.1 <=2.0.0, version solving failed.
pub get failed (1)

**Comment by uppercase-army** [comment]
@ArcticZeroo  bump

**Comment by Atulin** [comment]
Wanted to use it as well, noticed the same thing. Bump.
