### ISSUE TITLE
Has the plugin been abandoned?

### ISSUE THREAD

**Issue by warriorCoder** [ArcticZeroo/flutter-search-bar#34]
I can't find the package in the pub.dart.org site any longer and seeing a bunch of Issues a few PRs and no movement I'm wondering if this package has been abandoned.

**Comment by zinwalin** [comment]
same here.

**Comment by ArcticZeroo** [comment]
Sorry, it kind of was abandoned for a while due to university and work. I should be active again on GitHub if anyone would like to help contribute, and I will be updating it now. Probably slightly too late for your use case though, sorry!
